name: B_s_BeePost
version: '2.0'
main: biraw.online.b_s_BeePost.B_s_BeePost
author: [BiRaw]
api-version: '1.20'
depend: [SealLib]
permissions:
  b_s_bee_post.notify:
    description: Notify when a new update is released
    default: op